set(MICROVERSE_HEADERS_
		"Celestial/Gravity.hpp"
		"Celestial/ICelestial.hpp"
		"Celestial/Materials/MaterialGasGiant.hpp"
		"Celestial/Materials/MaterialRing.hpp"
		"Celestial/Orbit.hpp"
		"Celestial/Planet.hpp"
		"Celestial/Ring.hpp"
		"Celestial/Star.hpp"
		"Chunks/MaterialChunk.hpp"
		"Chunks/MeshChunk.hpp"
		"Chunks/QuadtreeChunk.hpp"
		"Configs/ConfigManager.hpp"
		"MainRenderer.hpp"
		"MainUpdater.hpp"
		"Post/Filters/FilterDamage.hpp"
		"Scenes/FpsCamera.hpp"
		"Scenes/FpsPlayer.hpp"
		"Scenes/Scene1.hpp"
		"Uis/Navigation/ContentExit.hpp"
		"Uis/Navigation/UiNavigation.hpp"
		"Uis/Navigation/UiTab.hpp"
		"Uis/OverlayDebug.hpp"
		"World/World.hpp"
)

set(MICROVERSE_SOURCES_
		"Celestial/Gravity.cpp"
		"Celestial/Materials/MaterialGasGiant.cpp"
		"Celestial/Materials/MaterialRing.cpp"
		"Celestial/Orbit.cpp"
		"Celestial/Planet.cpp"
		"Celestial/Ring.cpp"
		"Celestial/Star.cpp"
		"Chunks/MaterialChunk.cpp"
		"Chunks/MeshChunk.cpp"
		"Chunks/QuadtreeChunk.cpp"
		"Configs/ConfigManager.cpp"
		"Main.cpp"
		"MainRenderer.cpp"
		"MainUpdater.cpp"
		"Microverse.rc"
		"Post/Filters/FilterDamage.cpp"
		"Scenes/FpsCamera.cpp"
		"Scenes/FpsPlayer.cpp"
		"Scenes/Scene1.cpp"
		"Uis/Navigation/ContentExit.cpp"
		"Uis/Navigation/UiNavigation.cpp"
		"Uis/Navigation/UiTab.cpp"
		"Uis/OverlayDebug.cpp"
		"World/World.cpp"
)

source_group("Header Files" FILES ${MICROVERSE_HEADERS_})
source_group("Source Files" FILES ${MICROVERSE_SOURCES_})

set(MICROVERSE_SOURCES
		${MICROVERSE_HEADERS_}
		${MICROVERSE_SOURCES_}
)
