set(MICROVERSE_HEADERS_
        "Configs/ConfigManager.hpp"
        "Post/Filters/FilterDamage.hpp"
        "MainRenderer.hpp"
        "Celestial/ICelestial.hpp"
        "Celestial/Orbit.hpp"
        "Celestial/Gravity.hpp"
        "Celestial/Planet.hpp"
        "Celestial/Star.hpp"
        "MainUpdater.hpp"
        "Scenes/FpsCamera.hpp"
        "Scenes/FpsPlayer.hpp"
        "Scenes/Scene1.hpp"
        "Uis/Navigation/ContentExit.hpp"
        "Uis/Navigation/UiNavigation.hpp"
        "Uis/Navigation/UiTab.hpp"
        "Uis/OverlayDebug.hpp"
        "Uis/UiInventory.hpp"
        "Chunks/QuadtreeChunk.hpp"
        "Chunks/MaterialChunk.hpp"
        "Chunks/MeshChunk.hpp"
        "Waters/MaterialWater.hpp"
        "Waters/MeshWater.hpp"
        "World/World.hpp"
)

set(MICROVERSE_SOURCES_
        "Microverse.rc"
        "Configs/ConfigManager.cpp"
        "Post/Filters/FilterDamage.cpp"
        "Main.cpp"
        "MainRenderer.cpp"
        "Celestial/Gravity.cpp"
        "Celestial/Planet.cpp"
        "Celestial/Star.cpp"
        "Celestial/Orbit.cpp"
        "MainUpdater.cpp"
        "Scenes/FpsCamera.cpp"
        "Scenes/FpsPlayer.cpp"
        "Scenes/Scene1.cpp"
        "Uis/Navigation/ContentExit.cpp"
        "Uis/Navigation/UiNavigation.cpp"
        "Uis/Navigation/UiTab.cpp"
        "Uis/OverlayDebug.cpp"
        "Uis/UiInventory.cpp"
        "Chunks/QuadtreeChunk.cpp"
        "Chunks/MaterialChunk.cpp"
        "Chunks/MeshChunk.cpp"
        "Waters/MaterialWater.cpp"
        "Waters/MeshWater.cpp"
        "World/World.cpp"
)

source_group("Header Files" FILES ${MICROVERSE_HEADERS_})
source_group("Source Files" FILES ${MICROVERSE_SOURCES_})

set(MICROVERSE_SOURCES
        ${MICROVERSE_HEADERS_}
        ${MICROVERSE_SOURCES_}
)
